### ISSUE TITLE
Make a release for Django 1.9 full support

### ISSUE THREAD

**Issue by gustavi** [marcgibbons/django-rest-swagger#395]
Could you make a release for official django 1.9 support ? It'll remove Warnings.

**Comment by gustavi** [comment]
@marcgibbons ?

**Comment by howardjones** [comment]
C:\Python27\lib\site-packages\rest_framework_swagger\urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead. 
    url(r'^api-docs/(?P<path>.*)/?$', SwaggerApiView.as_view(), name='django.swagger.api.view'),

**Comment by rodcarroll** [comment]
@ariovistus can you help with this?  I would like to see this released as well, thx.

**Comment by ariovistus** [comment]
well, 0.3.5 is out, can people confirm things are working?

**Comment by rodcarroll** [comment]
Thanks, will check it out

**Comment by gustavi** [comment]
Some news ?

**Comment by edmorley** [comment]
The Django 1.9 build is currently failing with:
```
Traceback (most recent call last):
  File "/home/travis/build/marcgibbons/django-rest-swagger/runtests.py", line 23, in <module>
    execute_from_command_line([sys.argv[0], "test"])
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/opt/python/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django_nose/__init__.py", line 4, in <module>
    from django_nose.runner import *
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django_nose/runner.py", line 44, in <module>
    from django_nose.plugin import DjangoSetUpPlugin, ResultPlugin, TestReorderer
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django_nose/plugin.py", line 8, in <module>
    from django_nose.testcases import FastFixtureTestCase
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django_nose/testcases.py", line 7, in <module>
    from django_nose.fixture_tables import tables_used_by_fixtures
  File "/home/travis/build/marcgibbons/django-rest-swagger/.tox/py27-django1.9-drf3.3/lib/python2.7/site-packages/django_nose/fixture_tables.py", line 13, in <module>
    from django.db.models import get_apps
ImportError: cannot import name get_apps
```

https://travis-ci.org/marcgibbons/django-rest-swagger/jobs/139124021

**Comment by marcgibbons** [comment]
Closing this out as support has been added some time ago. The latest 0.3.x series supports 1.8+, as does v2
