### ISSUE TITLE
Use ListSerializer with `'CharField' object has no attribute 'get_fields'` error

### ISSUE THREAD

**Issue by fanshuai** [marcgibbons/django-rest-swagger#413]
When I user Serializer Class like this:
```
class OfflineSerializer(serializers.Serializer):
    offline = serializers.ListSerializer(
        child=serializers.CharField(required=True), allow_empty=False
    )
```

But it raise an AttributeError exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_swagger/views.py", line 164, in get
    'models': generator.get_models(apis),
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_swagger/docgenerator.py", line 133, in get_models
    self._find_field_serializers(serializers)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_swagger/docgenerator.py", line 279, in _find_field_serializers
    serializers_set))
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_swagger/docgenerator.py", line 271, in _find_field_serializers
    fields = serializer().get_fields()
AttributeError: 'CharField' object has no attribute 'get_fields'
```

My django version is 1.9.2, django-rest-swagger version is 0.3.5.

This package is very useful for me, thanks.

**Comment by gcko** [comment]
I'm pretty sure you need to put the `required=True` as a argument of the `ListSerializer`, not of the `CharField`

**Comment by fanshuai** [comment]
I tested this situation, and without `required=True` or `allow_empty=False`, but still have the same problem.

**Comment by fanshuai** [comment]
Write like this is usable with my `django-rest-framework` api.

I think might be the `child` argument with `ListSerializer` does not support the type of outside `Serializer` like `CharField`, when `django-rest-swagger` try to get the `ListSerializer`'s `child` field info.

**Comment by angvp** [comment]
I'm having the same issue, any hints? (subscribing anyway)

**Comment by marcgibbons** [comment]
Closing out. Schema generation is now handled by DRF 3.4.
