### ISSUE TITLE
AttributeError: 'CreateOnlyDefault' object has no attribute 'is_update'

### ISSUE THREAD

**Issue by jxstanford** [marcgibbons/django-rest-swagger#417]
I'm getting this exception when navigating to the doc page.  While there, none of the endpoints will expand.  

I think it's probably related to declarations of model fields in the serializer.  The offending code is below.  Any ideas what might be going on here?  Looking at `CreateOnlyDefault`, is_update is only set when `set_context` is called, and apparently it isn't being called during API doc generation.

```
class Trail(models.Model):
    ...
    saved_search = models.ForeignKey(SavedSearch, on_delete=models.PROTECT,
                                     editable=False)


class TrailSerializer(serializers.ModelSerializer):

    ...
    saved_search = PrimaryKeyRelatedField(
        read_only=True, default=CreateOnlyDefault(TrailSavedSearchDefault()))

    class Meta:        # pylint: disable=C0111,C1001,W0232
        model = Trail
        # remove swift_password from response
        extra_kwargs = {'swift_password': {'write_only': True}}
```

And the exception:

```2016-03-10T03:10:07+0000 ERROR    django.request  Internal Server Error: /docs/api-docs/compliance
Traceback (most recent call last):
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/rest_framework_swagger/views.py", line 164, in get
    'models': generator.get_models(apis),
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 139, in get_models
    data = self._get_serializer_fields(serializer)
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 328, in _get_serializer_fields
    'defaultValue': get_default_value(field),
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 54, in get_default_value
    default_value = default_value()
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/rest_framework/fields.py", line 225, in __call__
    if self.is_update:
AttributeError: 'CreateOnlyDefault' object has no attribute 'is_update'
[10/Mar/2016 03:10:07] "GET /docs/api-docs/compliance HTTP/1.1" 500 134636```

**Comment by jxstanford** [comment]
A little digging suggest that this might be resolved in the next DRF release:

https://github.com/tomchristie/django-rest-framework/pull/2619

**Comment by marcgibbons** [comment]
Closing out.
