### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by vaibhav-jain** [marcgibbons/django-rest-swagger#555]
I am getting HTTP 500 error in various API endpoints. . . 

```
Django v1.9
django-rest-swagger v0.3.10

```

```
ERROR:django.request: Internal Server Error: /v1/docs/api-docs/v1/users (2016-10-02 07:05:18; base.py:284)
Traceback (most recent call last):
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/views.py", line 166, in get
    'apis': generator.generate(apis),
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 53, in generate
    'operations': self.get_operations(api, apis),
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 88, in get_operations
    serializer = self._get_method_serializer(method_introspector)
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 209, in _get_method_serializer
    serializer = method_inspector.get_response_serializer_class()
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 256, in get_response_serializer_class
    serializer = self.get_serializer_class()
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 249, in get_serializer_class
    serializer = self.ask_for_serializer_class()
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 218, in ask_for_serializer_class
    view = self.create_view()
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 697, in create_view
    view = super(ViewSetMethodIntrospector, self).create_view()
  File "/home/prime/.virtualenvs/omapi/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 239, in create_view
    view.kwargs.update(self.parent.pattern.default_args)

```

**Comment by marcgibbons** [comment]
@vaibhav-jain I'm afraid I don't have enough information to assist. With that said, 0.3.x is being discontinued and would suggest to upgrade to the latest version.
