### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by alaminopu** [marcgibbons/django-rest-swagger#582]
Getting error with Django-rest-framework 3.5.3 and django-rest-swagger 2.1.0

Here is my view for Swagger

```python
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.schemas import SchemaGenerator
from rest_framework.views import APIView
from rest_framework_swagger import renderers


class SwaggerSchemaView(APIView):
    type = 'basic'
    permission_classes = [AllowAny]
    renderer_classes = [
        renderers.OpenAPIRenderer,
        renderers.SwaggerUIRenderer
    ]

    def get(self, request):
        generator = SchemaGenerator()
        schema = generator.get_schema(request=request)
        print schema

        return Response(schema)
```

Error message - 

```bash
Internal Server Error: /api/docs/
Traceback (most recent call last):
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alamin/pyserver/moqbank/projectile/core/views/api_docs.py", line 18, in get
    schema = generator.get_schema(request=request)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 242, in get_schema
    links = self.get_links(request)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 273, in get_links
    link = self.get_link(path, method, view)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 372, in get_link
    fields += self.get_serializer_fields(path, method, view)
  File "/home/alamin/Envs/moqbank/local/lib/python2.7/site-packages/rest_framework/schemas.py", line 499, in get_serializer_fields
    type=types_lookup[field]
TypeError: __new__() got an unexpected keyword argument 'type'
[10/Nov/2016 07:48:25] "GET /api/docs/ HTTP/1.1" 500 21270

```

**Comment by kevin-brown** [comment]
There's a good chance you need to upgrade your versions of coreapi. Support for typing was added in a newer version of coreapi.

**Comment by marcgibbons** [comment]
@alaminopu Did try upgrading coreapi and openapi-codec to the latest?

**Comment by alaminopu** [comment]
@kevin-brown Thanks for your comment.  It worked after upgrading coreapi.
