### ISSUE TITLE
OrderingFilter object has no attribute 'get_schema_fields'

### ISSUE THREAD

**Issue by dhm116** [marcgibbons/django-rest-swagger#585]
Seeing the following error when attempting to render the swagger docs:

```
Traceback (most recent call last):
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/rest_framework_swagger/views.py", line 29, in get
    schema = generator.get_schema(request=request)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/rest_framework/schemas.py", line 242, in get_schema
    links = self.get_links(request)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/rest_framework/schemas.py", line 273, in get_links
    link = self.get_link(path, method, view)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/rest_framework/schemas.py", line 374, in get_link
    fields += self.get_filter_fields(path, method, view)
  File "/Users/dmccall/Desktop/tap-vagrant/tap/antietam_django/venv/lib/python2.7/site-packages/rest_framework/schemas.py", line 524, in get_filter_fields
    fields += filter_backend().get_schema_fields(view)
AttributeError: 'OrderingFilter' object has no attribute 'get_schema_fields'
```

This is with `django-rest-swagger == 2.0.7`, `django-filter == 0.15.3` and `django == 1.10.3`

I haven't had a chance to dig around in the DRF swagger codebase yet to see if there's a simple workaround, but I thought I'd open this issue since I hadn't seen it mentioned before.

**Comment by dhm116** [comment]
I think this is more relevant for DRF itself - closing for now
