### ISSUE TITLE
Segfault on installing in python3.7

### ISSUE THREAD

**Issue by h4ck3rm1k3** [marcgibbons/django-rest-swagger#764]
python3.7 -m pip install django-rest-swagger segfaults
see bug report here for stacktrace and details
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902835

Via the git gives
`python3.7 -m pip install -e git://github.com/marcgibbons/django-rest-swagger.git#egg=django-rest-swagger`
```
git://github.com/marcgibbons/django-rest-swagger.git#egg=django-rest-swagger
Obtaining django-rest-swagger from git+git://github.com/marcgibbons/django-rest-swagger.git#egg=django-rest-swagger
  Updating ./src/django-rest-swagger clone
Collecting coreapi>=2.3.0 (from django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/fc/3a/9dedaad22962770edd334222f2b3c3e7ad5e1c8cab1d6a7992c30329e2e5/coreapi-2.3.3-py2.py3-none-any.whl
Collecting openapi-codec>=1.3.1 (from django-rest-swagger)
Collecting djangorestframework>=3.5.4 (from django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/90/30/ad1148098ff0c375df2a30cc4494ed953cf7551fc1ecec30fc951c712d20/djangorestframework-3.8.2-py2.py3-none-any.whl
Collecting simplejson (from django-rest-swagger)
Collecting coreschema (from coreapi>=2.3.0->django-rest-swagger)
Collecting requests (from coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting itypes (from coreapi>=2.3.0->django-rest-swagger)
Collecting uritemplate (from coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/e5/7d/9d5a640c4f8bf2c8b1afc015e9a9d8de32e13c9016dcc4b0ec03481fb396/uritemplate-3.0.0-py2.py3-none-any.whl
Collecting jinja2 (from coreschema->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->coreschema->coreapi>=2.3.0->django-rest-swagger)
Installing collected packages: MarkupSafe, jinja2, coreschema, idna, urllib3, certifi, chardet, requests, itypes, uritemplate, coreapi, openapi-codec, djangorestframework, simplejson, django-rest-swagger
  Found existing installation: django-rest-swagger 2.2.0
    Uninstalling django-rest-swagger-2.2.0:
      Successfully uninstalled django-rest-swagger-2.2.0
  Running setup.py develop for django-rest-swagger
Successfully installed MarkupSafe-1.0 certifi-2018.4.16 chardet-3.0.4 coreapi-2.3.3 coreschema-0.0.4 django-rest-swagger djangorestframework-3.8.2 idna-2.7 itypes-1.1.0 jinja2-2.10 openapi-codec-1.3.2 requests-2.19.1 simplejson-3.16.0 uritemplate-3.0.0 urllib3-1.23
Segmentation fault
```

GDB Session
```
gdb python3.7
GNU gdb (GDB) 7.12.50.20161115-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3.7...Reading symbols from /usr/lib/debug/.build-id/97/f8466c869649387c4f4af6e36e6deef1337a8c.debug...done.
done.
(gdb) set args  -m pip install django-rest-swagger
(gdb) r
Starting program: /usr/bin/python3.7 -m pip install django-rest-swagger
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Collecting django-rest-swagger
  Using cached https://files.pythonhosted.org/packages/26/b0/1df8743c3150630c2ce1f98f9f0f451038e43fb58a68d5da7877754f37b7/django_rest_swagger-2.2.0-py2.py3-none-any.whl
Collecting openapi-codec>=1.3.1 (from django-rest-swagger)
Collecting coreapi>=2.3.0 (from django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/fc/3a/9dedaad22962770edd334222f2b3c3e7ad5e1c8cab1d6a7992c30329e2e5/coreapi-2.3.3-py2.py3-none-any.whl
Collecting simplejson (from django-rest-swagger)
Collecting djangorestframework>=3.5.4 (from django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/90/30/ad1148098ff0c375df2a30cc4494ed953cf7551fc1ecec30fc951c712d20/djangorestframework-3.8.2-py2.py3-none-any.whl
Collecting uritemplate (from coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/e5/7d/9d5a640c4f8bf2c8b1afc015e9a9d8de32e13c9016dcc4b0ec03481fb396/uritemplate-3.0.0-py2.py3-none-any.whl
Collecting coreschema (from coreapi>=2.3.0->django-rest-swagger)
Collecting requests (from coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting itypes (from coreapi>=2.3.0->django-rest-swagger)
Collecting jinja2 (from coreschema->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests->coreapi>=2.3.0->django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->coreschema->coreapi>=2.3.0->django-rest-swagger)
Installing collected packages: uritemplate, MarkupSafe, jinja2, coreschema, chardet, certifi, idna, urllib3, requests, itypes, coreapi, openapi-codec, simplejson, djangorestframework, django-rest-swagger
Successfully installed MarkupSafe-1.0 certifi-2018.4.16 chardet-3.0.4 coreapi-2.3.3 coreschema-0.0.4 django-rest-swagger-2.2.0 djangorestframework-3.8.2 idna-2.7 itypes-1.1.0 jinja2-2.10 openapi-codec-1.3.2 requests-2.19.1 simplejson-3.16.0 uritemplate-3.0.0 urllib3-1.23

Program received signal SIGSEGV, Segmentation fault.
0x000000000051cd94 in visit_decref (op=<optimized out>, data=<optimized out>, op=<optimized out>, data=<optimized out>)
    at ../Modules/gcmodule.c:271
271	../Modules/gcmodule.c: No such file or directory.
(gdb) bt
#0  0x000000000051cd94 in visit_decref (op=<optimized out>, data=<optimized out>, op=<optimized out>, 
    data=<optimized out>) at ../Modules/gcmodule.c:271
#1  0x00000000005afdac in dict_traverse.lto_priv () at ../Objects/dictobject.c:2978
#2  0x0000000000524e87 in subtract_refs (containers=<optimized out>) at ../Modules/gcmodule.c:296
#3  collect.lto_priv () at ../Modules/gcmodule.c:853
#4  0x0000000000629639 in collect_with_callback (generation=generation@entry=2) at ../Modules/gcmodule.c:1028
#5  0x000000000062969a in PyGC_Collect () at ../Modules/gcmodule.c:1573
#6  0x0000000000631ba9 in Py_FinalizeEx () at ../Python/pylifecycle.c:1087
#7  0x0000000000631cc8 in Py_Exit (sts=0) at ../Python/pylifecycle.c:2133
#8  0x000000000062ee60 in handle_system_exit () at ../Python/pythonrun.c:636
#9  0x000000000062ee8c in PyErr_PrintEx () at ../Python/pythonrun.c:646
#10 0x0000000000650848 in pymain_run_module.lto_priv () at ../Modules/main.c:320
#11 0x00000000004bccf1 in pymain_run_python (pymain=0x7fffffffe1e0) at ../Modules/main.c:2517
#12 pymain_main.constprop () at ../Modules/main.c:2662
#13 0x000000000064a71f in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at ../Modules/main.c:2697
#14 0x00007ffff6c3fa87 in __libc_start_main (main=0x4bbce0 <main>, argc=5, argv=0x7fffffffe408, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe3f8) at ../csu/libc-start.c:310
#15 0x00000000005e25ca in _start () at ../Objects/obmalloc.c:1705
(gdb) 
```

**Comment by h4ck3rm1k3** [comment]
I think it might be because of simplejson https://github.com/simplejson/simplejson/issues/227

**Comment by h4ck3rm1k3** [comment]
Resolved by installing simplejson from git not pip
